In [1]:
import numpy as np


In [2]:
data = np.array([[ 1., -1.,  2., 1],
                 [ 2.,  0.,  0., 1],
                 [ 0.,  1., -1., 1],
                 [ -1.,  1., 3., 1],
                 [ 3.,  1., 1., 1]])

In [3]:
class CustomRobustScaler:

    def __init__(self):
        pass

    def fit_transform(self,data: np.ndarray) -> np.ndarray:
        median = np.median(a= data, axis = 0) # compute the min
        first_quartile = np.percentile(a= data, axis=0, q=25)# compute the max
        three_quartile = np.percentile(a= data, axis=0, q=75)# compute the max
        diff = three_quartile - first_quartile
        mask = diff !=0 # compute the denominator

        scaled_data = np.full_like(data, fill_value=0) 

        scaled_data[:, mask] = (data[:, mask] -median[mask]) / diff[mask]

        return scaled_data

In [5]:
scaler = CustomRobustScaler()
scaled_data = scaler.fit_transform(data)
scaled_data

array([[ 0. , -2. ,  0.5,  0. ],
       [ 0.5, -1. , -0.5,  0. ],
       [-0.5,  0. , -1. ,  0. ],
       [-1. ,  0. ,  1. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ]])

In [6]:
from sklearn.preprocessing import RobustScaler

rub_scaler = RobustScaler()

scaled_data1 = rub_scaler.fit_transform(data)
scaled_data1

array([[ 0. , -2. ,  0.5,  0. ],
       [ 0.5, -1. , -0.5,  0. ],
       [-0.5,  0. , -1. ,  0. ],
       [-1. ,  0. ,  1. ,  0. ],
       [ 1. ,  0. ,  0. ,  0. ]])

In [7]:
scaled_data1 == scaled_data

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])