In [20]:
import numpy as np
import pandas as pd
from typing import Dict, List, Tuple

In [69]:
class CustomOneHotEncoder:

    def __init__(self):
        self.cat_to_numb: Dict[str,List[int]] = {}
        self.numb_to_cat: Dict[Tuple[int],str] = {}
        self.categories: List[str] = []

    def __categories(self, data: np.ndarray) -> List:
        
        for index in range(data.shape[1]):
            self.categories += list(np.unique(data[:,index]))
        
    
    def __map_cat2numb(self) -> Dict:

        n = len(self.categories)
        for index, item in enumerate(self.categories) :
            don = [0 for _ in range(n)]
            don[index] = 1
            self.cat_to_numb[item] = don
        

    def __map_num2cat(self):
        if self.category_to_number:
            self.number_category = {tuple(value):key for key, value in self.category_to_number.items()}
    
    def fit_transform(self, data: np.ndarray):
        self.__categories(data)
        self.__map_cat2numb()
        
        n, p= data.shape
        k= len(self.categories) 

        array = np.empty((0, k))
        
        for line in range(n):
            arr = np.zeros((1, k))
            for col in range(p) :
                arr += np.array(self.cat_to_numb[data[line, col]])
            array = np.concatenate((array, arr), axis = 0)
        return array
        # mapped_data = np.array([[self.cat_to_numb[item] for item in row] for row in data], dtype=object)
        # return mapped_data.sum(axis=1)
    
    def inverse_transforme(self):
        pass
        
    
        

In [70]:
data = {'Employee id': [10, 20, 15, 25, 30],
        'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
        'Remarks': ['Good', 'Nice', 'Good', 'Great', 'Nice'],
        }
#Converting into a Pandas dataframe
df = pd.DataFrame(data)

array = df[['Gender', 'Remarks']].map(lambda x : x.lower()).to_numpy()
array

array([['male', 'good'],
       ['female', 'nice'],
       ['female', 'good'],
       ['male', 'great'],
       ['female', 'nice']], dtype=object)

In [71]:
cust_encoder = CustomOneHotEncoder()

encoded_data = cust_encoder.fit_transform(array)
encoded_data

array([[0., 1., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.]])

In [47]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

encoded_data1 = encoder.fit_transform(array)
print(encoded_data1)

[[0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1.]]


In [50]:
np.all(encoded_data1) == np.all(encoded_data)

True