In [1]:
import numpy as np

In [2]:
data = np.array([[ 1., -1.,  2., 1],
                 [ 2.,  0.,  0., 1],
                 [ 0.,  1., -1., 1],
                 [ -1.,  1., 3., 1],
                 [ 3.,  1., 1., 1]])

In [3]:
class CustomMinMaxScaler:

    def __init__(self):
        pass

    def fit_transform(self,data: np.ndarray) -> np.ndarray:
        min_ = np.min(a= data, axis = 0) # compute the min
        max_= np.max(a= data, axis=0)# compute the max
        diff = max_ - min_
        mask = diff !=0 # compute the denominator

        scaled_data = np.full_like(data, fill_value=0) 

        scaled_data[:, mask] = (data[:, mask] -min_[mask]) / diff[mask]

        return scaled_data

In [4]:
scaler = CustomMinMaxScaler()

scaled_data = scaler.fit_transform(data)
scaled_data

array([[0.5 , 0.  , 0.75, 0.  ],
       [0.75, 0.5 , 0.25, 0.  ],
       [0.25, 1.  , 0.  , 0.  ],
       [0.  , 1.  , 1.  , 0.  ],
       [1.  , 1.  , 0.5 , 0.  ]])

In [5]:
from sklearn.preprocessing import MinMaxScaler

scaler1 = MinMaxScaler()

scaled_data1 = scaler1.fit_transform(data)
scaled_data1

array([[0.5 , 0.  , 0.75, 0.  ],
       [0.75, 0.5 , 0.25, 0.  ],
       [0.25, 1.  , 0.  , 0.  ],
       [0.  , 1.  , 1.  , 0.  ],
       [1.  , 1.  , 0.5 , 0.  ]])

In [6]:
scaled_data1 == scaled_data

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])