In [28]:
import numpy as np

In [23]:
class CustomStandardScaler:

    def __init__(self):
        pass

    def fit_transform(self,data: np.ndarray) -> np.ndarray:
        mean = np.mean(a= data, axis = 0) # compute the mean
        std = np.std(a= data, axis=0)# compute the standard deviation
        mask = std !=0 # compute mask in order to avoid deviding by zero

        scaled_data = np.full_like(data, fill_value=0) 

        scaled_data[:, mask] = (data[:, mask] - mean[mask])/ std[mask]

        return scaled_data

In [24]:
data = np.array([[ 1., -1.,  2., 1],
                 [ 2.,  0.,  0., 1],
                 [ 0.,  1., -1., 1],
                 [ -1.,  1., 3., 1],
                 [ 3.,  1., 1., 1]])

In [25]:
custom_scaler = CustomStandardScaler()

transform_data = custom_scaler.fit_transform(data)
transform_data

array([[ 0.        , -1.75      ,  0.70710678,  0.        ],
       [ 0.70710678, -0.5       , -0.70710678,  0.        ],
       [-0.70710678,  0.75      , -1.41421356,  0.        ],
       [-1.41421356,  0.75      ,  1.41421356,  0.        ],
       [ 1.41421356,  0.75      ,  0.        ,  0.        ]])

In [26]:
from sklearn.preprocessing import StandardScaler

standard = StandardScaler()

scaled_data = standard.fit_transform(data)
scaled_data

array([[ 0.        , -1.75      ,  0.70710678,  0.        ],
       [ 0.70710678, -0.5       , -0.70710678,  0.        ],
       [-0.70710678,  0.75      , -1.41421356,  0.        ],
       [-1.41421356,  0.75      ,  1.41421356,  0.        ],
       [ 1.41421356,  0.75      ,  0.        ,  0.        ]])

In [27]:
scaled_data == transform_data

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])